org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
kotlin.mpp.androidSourceSetLayoutVersion=2

POM_GROUP_ID=io.github.sigkitten.hairball
VERSION_NAME=0.0.0-SNAPSHOT
POM_NAME=Hairball
POM_DESCRIPTION=Cross-platform markdown parsing and rendering libraries for Apple and Android.
POM_URL=https://github.com/sigkitten/swift-md
POM_LICENSE_NAME=MIT
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo
POM_DEVELOPER_ID=sigkitten
POM_DEVELOPER_NAME=sigkitten
POM_DEVELOPER_URL=https://github.com/sigkitten
POM_SCM_URL=https://github.com/sigkitten/swift-md
POM_SCM_CONNECTION=scm:git:https://github.com/sigkitten/swift-md.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/sigkitten/swift-md.git

ANDROID_COMPILE_SDK=35
ANDROID_TARGET_SDK=35
ANDROID_MIN_SDK=26
